packages:
  - .
  - docs

allowBuilds:
  "@parcel/watcher": true
  esbuild: true

catalog:
  "@astrojs/markdown-satteri": ^0.4.1
  "@astrojs/mdx": ^8.0.1
  "@types/node": ^26.6.2
  "@vitest/browser-playwright": 5.0.1
  "@vitest/coverage-istanbul": 5.0.1
  astro: ^7.3.3
  bumpp: ^12.3.0
  playwright: ^1.63.0
  sass: ^1.104.1
  sharp: ^0.35.4
  subset-font: ^2.7.0
  typescript: npm:typescript-native-bridge@^6.0.3-bridge.17.tsgo.7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-commit.6b26ec56e76df770e2aa5ad78571d42d20b5383c
  vite-plus: 0.0.0-commit.6b26ec56e76df770e2aa5ad78571d42d20b5383c
  vitest: 5.0.1

catalogMode: strict

linkWorkspacePackages: true

minimumReleaseAgeExclude:
  - "@voidzero-dev/vite-plus-core@0.0.0-commit.6b26ec56e76df770e2aa5ad78571d42d20b5383c"
  - "@voidzero-dev/vite-plus-darwin-arm64@0.0.0-commit.6b26ec56e76df770e2aa5ad78571d42d20b5383c"
  - "@voidzero-dev/vite-plus-darwin-x64@0.0.0-commit.6b26ec56e76df770e2aa5ad78571d42d20b5383c"
  - "@voidzero-dev/vite-plus-linux-arm64-gnu@0.0.0-commit.6b26ec56e76df770e2aa5ad78571d42d20b5383c"
  - "@voidzero-dev/vite-plus-linux-arm64-musl@0.0.0-commit.6b26ec56e76df770e2aa5ad78571d42d20b5383c"
  - "@voidzero-dev/vite-plus-linux-x64-gnu@0.0.0-commit.6b26ec56e76df770e2aa5ad78571d42d20b5383c"
  - "@voidzero-dev/vite-plus-linux-x64-musl@0.0.0-commit.6b26ec56e76df770e2aa5ad78571d42d20b5383c"
  - "@voidzero-dev/vite-plus-win32-arm64-msvc@0.0.0-commit.6b26ec56e76df770e2aa5ad78571d42d20b5383c"
  - "@voidzero-dev/vite-plus-win32-x64-msvc@0.0.0-commit.6b26ec56e76df770e2aa5ad78571d42d20b5383c"
  - vite-plus@0.0.0-commit.6b26ec56e76df770e2aa5ad78571d42d20b5383c

overrides:
  vite@*: "catalog:"
  playwright@*: "catalog:"
  vitest@*: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
